default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  port: 5432
  host:     <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :hostname) %>
  database: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :database) %>
  # username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :username) %>
  # password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :password) %>

test:
  <<: *default
  hostname: "localhost"
  database: "octopath_notebook_test"
  username: "postgres"
  password: "postgres"

development:
  <<: *default

production:
  <<: *default
  username: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :username) %>
  password: <%= Rails.application.credentials.dig(Rails.env.to_sym, :db, :password) %>
