:concurrency: 1
:reconnect_attempts: 1
:logfile: /dev/null
:redis:
  :url: <%= ENV.fetch("REDIS_URL") { puts("'REDIS_URL' not set")} %>
:queues:
  - "default"
  - "low_priority"
  - "active_storage_purge"
  - "active_storage_analysis"
